=== BackupTheBerlios/bisj2ee/XMLTECH/Uebung03/Uebung03.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by kossi (NONE) -->
<xs:schema targetNamespace="http://www.my-webbase.de/xml" xmlns="http://www.my-webbase.de/xml" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="workgroup">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="news">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="notice" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="date" type="xs:date" minOccurs="0"/>
									</xs:sequence>
									<xs:attribute name="type" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="Projektstart"/>
												<xs:enumeration value="Update"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="keyref" type="xs:IDREF" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="teaching">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="courses" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="term">
											<xs:complexType>
												<xs:attribute name="season" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:enumeration value="WS"/>
															<xs:enumeration value="SS"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="year" type="xs:gYear" use="required"/>
											</xs:complexType>
										</xs:element>
										<xs:choice>
											<xs:element name="href" type="xs:anyURI"/>
											<xs:element name="course" minOccurs="0" maxOccurs="unbounded">
												<xs:complexType>
													<xs:simpleContent>
														<xs:extension base="xs:string">
															<xs:attribute name="courseType" use="required">
																<xs:simpleType>
																	<xs:restriction base="xs:string">
																		<xs:enumeration value="lecture"/>
																		<xs:enumeration value="practical"/>
																		<xs:enumeration value="project"/>
																		<xs:enumeration value="seminar"/>
																	</xs:restriction>
																</xs:simpleType>
															</xs:attribute>
															<xs:attribute name="href" type="xs:anyURI" use="optional"/>
														</xs:extension>
													</xs:simpleContent>
												</xs:complexType>
											</xs:element>
										</xs:choice>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="assignments" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="description" type="xs:string"/>
										<xs:element name="advices" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="advice" minOccurs="0" maxOccurs="unbounded">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute name="href" type="xs:anyURI" use="optional"/>
																	<xs:attribute name="id" type="xs:ID" use="required"/>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="href" type="xs:anyURI" use="optional"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="research">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="projects" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="project" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="name" type="xs:string"/>
													<xs:element name="brief-description" type="xs:string" minOccurs="0"/>
													<xs:element name="description">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="english-version" type="xs:anyURI" minOccurs="0"/>
																<xs:choice>
																	<xs:element name="href" type="xs:anyURI"/>
																	<xs:sequence>
																		<xs:element name="abstract" type="xs:string"/>
																		<xs:element name="initiators" type="PersonList" minOccurs="0"/>
																		<xs:element name="contacts" minOccurs="0">
																			<xs:complexType>
																				<xs:choice minOccurs="0" maxOccurs="unbounded">
																					<xs:element name="contact" type="Person" minOccurs="0"/>
																					<xs:element name="REF" type="xs:IDREF" minOccurs="0"/>
																				</xs:choice>
																			</xs:complexType>
																		</xs:element>
																		<xs:element name="workpackages" minOccurs="0">
																			<xs:complexType>
																				<xs:sequence>
																					<xs:element name="package" minOccurs="0" maxOccurs="unbounded">
																						<xs:complexType>
																							<xs:simpleContent>
																								<xs:extension base="xs:string">
																									<xs:attribute name="id" type="xs:ID" use="required"/>
																									<xs:attribute name="href" type="xs:anyURI" use="optional"/>
																								</xs:extension>
																							</xs:simpleContent>
																						</xs:complexType>
																					</xs:element>
																				</xs:sequence>
																			</xs:complexType>
																		</xs:element>
																		<xs:element name="publications" minOccurs="0">
																			<xs:complexType>
																				<xs:sequence>
																					<xs:element name="publication" minOccurs="0" maxOccurs="unbounded">
																						<xs:complexType>
																							<xs:sequence>
																								<xs:element name="title" type="xs:string"/>
																								<xs:element ref="authors"/>
																							</xs:sequence>
																							<xs:attribute name="href" type="xs:anyURI" use="optional"/>
																						</xs:complexType>
																					</xs:element>
																				</xs:sequence>
																			</xs:complexType>
																		</xs:element>
																	</xs:sequence>
																</xs:choice>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="partner" minOccurs="0" maxOccurs="unbounded">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute name="href" type="xs:anyURI" use="optional"/>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
													<xs:element name="sponsor" minOccurs="0" maxOccurs="unbounded">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute name="href" type="xs:anyURI" use="optional"/>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="id" type="xs:ID" use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="topic" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="tasks" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="task" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="results" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="result" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute name="href" type="xs:anyURI" use="optional"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="people">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="member" type="Member" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
						<xs:attribute name="fomerMembersURL" type="xs:anyURI" use="optional"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="info">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="university">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="href" type="xs:anyURI" use="optional"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="department">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="href" type="xs:anyURI" use="optional"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="institute">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="href" type="xs:anyURI" use="optional"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="address" type="Address"/>
							<xs:element name="telephone">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="prefix" type="xs:string"/>
										<xs:element name="default-directdial" type="xs:string"/>
										<xs:element name="fax-directdial" type="xs:string" minOccurs="0"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="public-office">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="address" type="Address"/>
										<xs:element name="open" type="xs:string" maxOccurs="unbounded"/>
										<xs:element name="location-image" type="xs:anyURI" minOccurs="0"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="logo" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:anyURI">
											<xs:attribute name="alt" type="xs:string" use="optional"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="accessroute" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="href" type="xs:anyURI" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element ref="authors"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="authors" type="PersonList"/>
	<xs:element name="personREF" type="xs:IDREF"/>
	<xs:complexType name="Address">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="street" type="xs:string"/>
			<xs:element name="zipcode" type="xs:string"/>
			<xs:element name="city"/>
			<xs:element name="country"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Name">
		<xs:sequence>
			<xs:element name="title" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="first" type="xs:string"/>
			<xs:element name="middle" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="last" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Person">
		<xs:sequence>
			<xs:element name="ID" type="xs:ID"/>
			<xs:element name="name" type="Name"/>
			<xs:element name="address" type="Address" minOccurs="0"/>
			<xs:element name="phone" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="email" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="href" type="xs:anyURI" use="optional"/>
	</xs:complexType>
	<xs:complexType name="Initiator">
		<xs:complexContent>
			<xs:extension base="Person">
				<xs:sequence>
					<xs:element name="role" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="Member">
		<xs:complexContent>
			<xs:extension base="Initiator">
				<xs:sequence>
					<xs:element name="directdial" type="xs:string" minOccurs="0"/>
					<xs:element name="assigned-projects" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="projectREF" type="xs:IDREF" minOccurs="0" maxOccurs="unbounded"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="PersonList">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="person" type="Person"/>
			<xs:element ref="personREF"/>
		</xs:choice>
	</xs:complexType>
</xs:schema>

=== BackupTheBerlios/bisj2ee/XMLTECH/Uebung03/Uebung03.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by kossi (NONE) -->
<?xml-stylesheet type="text/xsl" href="D:\Studium\XML-Technologien\XMLTECH\Uebung03\Uebung03.xslt"?>
<workgroup xmlns="http://www.my-webbase.de/xml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.my-webbase.de/xml
Uebung03.xsd" name="Netzbasierte Informationssysteme / Networked Informationsystems">
	<news>
		<notice type="Projektstart" keyref="project_06">
			<date>2004-02-08</date>
		</notice>
		<notice type="Projektstart" keyref="project_03">
			<date>2004-01-01</date>
		</notice>
		<notice type="Projektstart" keyref="project_11">
			<date>2004-01-01</date>
		</notice>
		<notice type="Projektstart" keyref="project_01">
			<date>2003-09-01</date>
		</notice>
		<notice type="Projektstart" keyref="project_02">
			<date>2003-07-01</date>
		</notice>
		<notice type="Update" keyref="advice_01">
			<date>2003-03-11</date>
		</notice>
	</news>
	<teaching>
		<courses>
			<term season="SS" year="2004"/>
			<course courseType="lecture" href="http://www.inf.fu-berlin.de/inst/ag-nbi/lehre/04/V_ALPIV/">Algorithmen und Programmierung IV	</course>
			<course courseType="lecture" href="http://www.inf.fu-berlin.de/inst/ag-nbi/lehre/04/V_XML/">XML Technologien</course>
			<course courseType="seminar" href="http://www.inf.fu-berlin.de/inst/ag-nbi/lehre/04/S_P2PNET/index.html">Peer-to-Peer-Netzwerke</course>
			<course courseType="practical" href="http://www.inf.fu-berlin.de/inst/ag-nbi/lehre/04/P_SW">Semantic Web</course>
		</courses>
		<courses>
			<term season="WS" year="2003"/>
			<href>http://www.inf.fu-berlin.de/inst/ag-nbi/lehre/AlteLehre.html</href>
		</courses>
		<assignments href="http://www.inf.fu-berlin.de/inst/ag-nbi/lehre/diploma.html">
			<description>Fortlaufend werden Diplom- und andere Arbeiten betreut. Sie können sich anhand der Liste macher Diplomarbeitsthemen orientieren.</description>
			<advices>
				<advice href="http://www.inf.fu-berlin.de/inst/ag-nbi/lehre/tipps/referatepapiere.pdf" id="advice_03">Referaten und Ausarbeitungen</advice>
				<advice href="http://www.inf.fu-berlin.de/inst/ag-nbi/lehre/tipps/diplomarbeiten.pdf" id="advice_02">Diplomarbeiten</advice>
				<advice href="http://www.inf.fu-berlin.de/inst/ag-nbi/lehre/seminare.html" id="advice_01">Ablauf und Leistungserbringung in Seminaren</advice>
			</advices>
		</assignments>
	</teaching>
	<research>
		<projects topic="Semantic Web">
			<project id="project_01">
				<name>Semantic Web in der Pathologie</name>
				<brief-description>An information retrieval system for images and text based on Semantic Web technologies for pathology focusing on lungdiseases.</brief-description>
				<description>
					<english-version>http://www.inf.fu-berlin.de/inst/ag-nbi/research/swpatho/swpathoEng.html</english-version>
					<abstract>Entwicklung, Implementierung und Evaluierung eines auf Semantic Web Technologien basierenden Bild- und Informationsretrievalsystems für die Digitale Pathologie am Beispiel von Lungenkrankheiten. Das Projekt entwickelt ein prototypisches System für Verarbeitung und Retrieval von Bildbeschreibungen und Befundberichten in der Pathologie, speziell für Lungenerkrankungen. Im Gegensatz zu heutigen Datenbanken soll die Information durchgehend semantisch annotiert und mit Ontologien verknüpft sein, was eine Recherche nach Inhalten gestattet. Das in den Bild- und Textdaten enthaltene Expertenwissen lässt sich damit anderen Anwendungsszenarien zugänglich und wiederverwendbar machen. Es kann zur Qualitätssicherung, zur Unterstützung von Diagnostik und Differentialdiagnose, zur statistischen Auswertung, zu Präsentationen und in der Lehre genutzt werden.
Bei der Erstellung von Befundberichten wird semantische Information durch computerlinguistische Analyse automatisch erfasst und in ein semantisches Netz eingefügt, das auf einem Pathologiespezifischen Modell basiert. Das System stellt diese Information dann für die unterschiedlichen Zwecke zur Verfügung. Eine Integrationskomponente versucht darüber hinaus, Informationen aus externen Wissensquellen einzubinden. Technologisch basiert das geplante System auf den Standards des Semantic Web wie XML, RDF und RuleML und anerkannten medizinischen Modellen und Standards (UMLS, HL7, SCORM).
					</abstract>
					<initiators>
						<person xsi:type="Initiator">
							<ID>initiator_01</ID>
							<name>
								<title>Dr. med.</title>
								<title>Dipl.med.Inf.(FH)</title>
								<first>Thomas</first>
								<last>Schrader</last>
							</name>
							<address>
								<name>Uni-Klinik Charité Institut für Pathologie</name>
								<street>Schumanstr. 20-21</street>
								<zipcode>10117</zipcode>
								<city>Berlin</city>
								<country>Deutschland</country>
							</address>
							<phone>030450536113</phone>
							<email>thomas.schrader@charite.de</email>
							<role>UICC-TPCC Administrator, Pathologe</role>
						</person>
						<person xsi:type="Initiator">
							<ID>initiator_02</ID>
							<name>
								<title>Prof.</title>
								<title>Dr.</title>
								<first>Manfred</first>
								<last>Strede</last>
							</name>
							<address>
								<name>Universität Potsdam Institut für Linguistik</name>
								<street>Postf. 601553</street>
								<zipcode>14415</zipcode>
								<city>Potsdam</city>
								<country>Deutschland</country>
							</address>
							<phone>03319772691</phone>
							<email>thomas.schrader@charite.de</email>
							<role>Professor für Angewandte Computerlinguistik</role>
						</person>
						<personREF>member_01</personREF>
					</initiators>
					<contacts>
						<REF>member_05</REF>
					</contacts>
					<workpackages>
						<package id="AP1" href="http://www.inf.fu-berlin.de/inst/ag-nbi/research/swpatho/ap1_150304.pdf">Entwurf und Entwicklung einer Beschreibungskomponente zur Erfassung und Repräsentation von Text- und Bildinformationen</package>
						<package id="AP2">Entwurf, Implementierung und Evaluation der Fachwissenskomponente</package>
						<package id="AP3">Entwurf und Implementierung einer Transformationskomponente zur Analyse und semantischen Repräsentation bestehender Befundberichte</package>
						<package id="AP4">Entwurf, Implementierung und Evaluation von Anwendungskomponenten</package>
						<package id="AP5">Entwurf und Implementierung von Integrationskomponenten</package>
						<package id="AP6">Systemvalidierung in der Anwendung</package>
						<package id="AP7">Projekt-, Qualitätsmanagement und Aussendarstellung</package>
					</workpackages>
					<publications>
						<publication href="http://www.inf.fu-berlin.de/inst/ag-nbi/research/swpatho/icwe04.pdf">
							<title>Engineering a Semantic Web for Pathology (ICWE'04 Conference)</title>
							<authors>
								<personREF>member_01</personREF>
								<personREF>member_05</personREF>
							</authors>
						</publication>
						<publication href="http://www.inf.fu-berlin.de/inst/ag-nbi/research/swpatho/TagungDeutscheGesellschaftPathologieRostock.doc">
							<title>Tagung Deutsche Gesellschaft für Pathologie Rostock 2004</title>
							<authors>
								<personREF>member_01</personREF>
							</authors>
						</publication>
					</publications>
				</description>
				<partner>Humboldt-Universität zu Berlin</partner>
				<partner>Universität Potsdam</partner>
			</project>
			<project id="project_02">
				<name>Wissensnetze</name>
				<brief-description>Studies  the impact of semantic technologies from the business and the technical viewpoint to make predictions about the influence of the new technologies on markets, enterprises and individuals.</brief-description>
				<description>
					<href>http://www.inf.fu-berlin.de/inst/ag-nbi/research/wissensnetze</href>
				</description>
				<sponsor>Berlin Research Centre for the Internet Economy InterVal</sponsor>
			</project>
			<project id="project_03">
				<name>KnowledgeWeb</name>
				<brief-description>Network of Excellence. Realizing the Semantic Web</brief-description>
				<description>
					<href>http://knowledgeweb.semanticweb.org</href>
				</description>
				<sponsor>EU FP6</sponsor>
			</project>
			<project id="project_04">
				<name>OntoWeb</name>
				<brief-description>Ontology-based information exchange for knowledge management and electronic commerce.</brief-description>
				<description>
					<href>http://www.ontoweb.org</href>
				</description>
				<sponsor>European Union</sponsor>
			</project>
			<project id="project_05">
				<name>Agentlink III</name>
				<brief-description>Network of Excellence in Agent research.</brief-description>
				<description>
					<href>http://www.agentlink.org</href>
				</description>
				<sponsor>European Union</sponsor>
			</project>
		</projects>
		<projects topic="XML Technologies">
			<project id="project_06">
				<name>XML Sicherheitsdienste fuer GBIF-D</name>
				<brief-description>Providing XML security services and access controls for the German node of the Global Biodiversity Information Facility.</brief-description>
				<description>
					<href>http://www.inf.fu-berlin.de/inst/ag-nbi/research/IBIS-D</href>
				</description>
				<partner href="http://www.bgbm.org/">Botanischer Garten und Botanisches Museum Berlin</partner>
				<partner href="http://www.gbif.de/">German node of the Global Biodiversity Information Facility</partner>
				<sponsor>BMBF</sponsor>
			</project>
			<project id="project_07">
				<name>SYNTHESYS</name>
				<brief-description>Develop authentication services for system access in DiGIR/ABCD, so that restricted data access can be granted to appropriate end-users.</brief-description>
				<description>
					<href>http://www.synthesys.info</href>
				</description>
				<partner href="http://www.bgbm.org/">Botanischer Garten und Botanisches Museum Berlin</partner>
				<sponsor>European Union</sponsor>
			</project>
			<project id="project_08">
